version: "3.9"

networks:
  desafiovotacao-network:
    driver: bridge

services:
  desafiovotacao-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "3306:3306"
    networks:
      - desafiovotacao-network